// Generated by scripts/generate-i18n-coverage.mjs. Do not edit manually.
export const translationCoverage = {
  en: {
    translatedUnits: 705,
    totalUnits: 705,
    percentage: 100,
  },
  ru: {
    translatedUnits: 695,
    totalUnits: 705,
    percentage: 99,
  },
} as const;
