// Generated by scripts/generate-i18n-coverage.mjs. Do not edit manually.
export const translationCoverage = {
  en: {
    translatedUnits: 708,
    totalUnits: 708,
    percentage: 100,
  },
  ru: {
    translatedUnits: 708,
    totalUnits: 708,
    percentage: 100,
  },
} as const;
