// Generated by scripts/generate-i18n-coverage.mjs. Do not edit manually.
export const translationCoverage = {
  en: {
    translatedUnits: 754,
    totalUnits: 754,
    percentage: 100,
  },
  ru: {
    translatedUnits: 694,
    totalUnits: 754,
    percentage: 92,
  },
} as const;
