[package]
name = "easy-cut-desktop"
version.workspace = true
description = "Easy Cut desktop application"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "easy_cut_desktop_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
wait-timeout = "0.2.1"
