[package]
name = "easytrim-editor-desktop"
version.workspace = true
description = "EasyTrim Editor desktop application"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "easytrim_editor_desktop_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-opener = "2.5.4"
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.10.1"
wait-timeout = "0.2.1"
