import { type MutableRefObject, useCallback } from "react";

import { clampPlaybackMicros } from "@/domain/playback";
import type { TrimRange } from "@/domain/trim";
import { diagnostics } from "@/lib/diagnostics";

import type { FrameShuttleDirection } from "../lib/editor-shortcuts";

import type { usePlaybackModes } from "./usePlaybackModes";

interface TimelineMediaEventsArgs {
  commitSeek: (micros: number) => void;
  currentPlayheadMicrosRef: MutableRefObject<number>;
  getMediaState: () => { currentTimeSeconds: number; paused: boolean; seeking: boolean } | null;
  handlePausePlayback: () => void;
  handlePlaybackBoundary: (micros: number) => boolean;
  handleShuttleEnd: (origin?: { id?: string; type: "internal" }) => void;
  isPlayingRef: MutableRefObject<boolean>;
  isSeekPending: () => boolean;
  onSetPlayhead: (micros: number) => void;
  pauseAudioPlayback: () => void;
  pauseMedia: () => void;
  pendingFrameStepSeekMicrosRef: MutableRefObject<number | null>;
  playbackModes: ReturnType<typeof usePlaybackModes>;
  playbackRequestedRef: MutableRefObject<boolean>;
  playMedia: () => Promise<void>;
  setIsPlaying: (playing: boolean) => void;
  shuttleDirectionRef: MutableRefObject<FrameShuttleDirection | 0>;
  startMediaPlayback: () => void;
  startPlayheadAnimation: () => void;
  stopPlayheadAnimation: () => void;
  timelineInteractionActiveRef: MutableRefObject<boolean>;
  transportSuspendedRef: MutableRefObject<boolean>;
  trimRef: MutableRefObject<TrimRange>;
}

function useTimelineMediaEvents({
  commitSeek,
  currentPlayheadMicrosRef,
  getMediaState,
  handlePausePlayback,
  handlePlaybackBoundary,
  handleShuttleEnd,
  isPlayingRef,
  isSeekPending,
  onSetPlayhead,
  pauseAudioPlayback,
  pauseMedia,
  pendingFrameStepSeekMicrosRef,
  playbackModes,
  playbackRequestedRef,
  playMedia,
  setIsPlaying,
  shuttleDirectionRef,
  startMediaPlayback,
  startPlayheadAnimation,
  stopPlayheadAnimation,
  timelineInteractionActiveRef,
  transportSuspendedRef,
  trimRef,
}: TimelineMediaEventsArgs) {
  const onTimeUpdate = useCallback(
    (seconds: number) => {
      if (
        shuttleDirectionRef.current !== 0 ||
        timelineInteractionActiveRef.current ||
        pendingFrameStepSeekMicrosRef.current !== null ||
        isSeekPending() ||
        getMediaState()?.seeking
      )
        return;
      const currentMicros = clampPlaybackMicros(
        seconds * 1_000_000,
        trimRef.current.sourceDurationMicros,
      );

      if (isPlayingRef.current) {
        handlePlaybackBoundary(currentMicros);
        return;
      }
      currentPlayheadMicrosRef.current = currentMicros;
      onSetPlayhead(currentMicros);
      if (currentMicros >= trimRef.current.sourceDurationMicros) stopPlayheadAnimation();
    },
    [
      currentPlayheadMicrosRef,
      getMediaState,
      handlePlaybackBoundary,
      isPlayingRef,
      isSeekPending,
      onSetPlayhead,
      pendingFrameStepSeekMicrosRef,
      shuttleDirectionRef,
      stopPlayheadAnimation,
      timelineInteractionActiveRef,
      trimRef,
    ],
  );

  const onPause = useCallback(() => {
    if (playbackRequestedRef.current && isSeekPending()) return;
    if (isPlayingRef.current) {
      // A pause generated by a transient browser seek is restored while the request remains active.
      void playMedia().catch(() => undefined);
      return;
    }
    playbackRequestedRef.current = false;
    isPlayingRef.current = false;
    setIsPlaying(false);
    pauseAudioPlayback();
    stopPlayheadAnimation();
    const mediaState = getMediaState();
    if (mediaState) onTimeUpdate(mediaState.currentTimeSeconds);
    diagnostics.event("playback.state.changed", {
      data: { status: "paused" },
      origin: { type: "internal" },
    });
  }, [
    getMediaState,
    isPlayingRef,
    isSeekPending,
    onTimeUpdate,
    pauseAudioPlayback,
    playMedia,
    playbackRequestedRef,
    setIsPlaying,
    stopPlayheadAnimation,
  ]);

  const onLoadedMetadata = useCallback(() => {
    commitSeek(currentPlayheadMicrosRef.current);
  }, [commitSeek, currentPlayheadMicrosRef]);

  const onPlay = useCallback(() => {
    if (transportSuspendedRef.current) {
      pauseMedia();
      return;
    }
    playbackRequestedRef.current = true;
    if (shuttleDirectionRef.current !== 0) {
      if (shuttleDirectionRef.current === 1) startPlayheadAnimation();
      return;
    }
    isPlayingRef.current = true;
    setIsPlaying(true);
    startPlayheadAnimation();
    diagnostics.event("playback.state.changed", {
      data: { status: "playing" },
      origin: { type: "internal" },
    });
  }, [
    isPlayingRef,
    playbackRequestedRef,
    pauseMedia,
    setIsPlaying,
    shuttleDirectionRef,
    startPlayheadAnimation,
    transportSuspendedRef,
  ]);

  const onEnded = useCallback(() => {
    diagnostics.event("playback.state.changed", {
      data: { status: "ended" },
      origin: { type: "internal" },
    });
    if (shuttleDirectionRef.current !== 0) {
      if (shuttleDirectionRef.current === 1) {
        const boundary = playbackModes.consumeSourceBoundary(
          trimRef.current.sourceDurationMicros,
          trimRef.current.sourceDurationMicros,
          1,
        );

        const boundaryAction = boundary.reached ? boundary.action : null;
        if (boundaryAction?.type === "restart") {
          commitSeek(boundaryAction.positionMicros);
          playbackModes.resetBoundary();
          startMediaPlayback();
          return;
        }
      }
      handleShuttleEnd({ type: "internal", id: "source-end" });
      return;
    }
    const mediaState = getMediaState();
    if (mediaState) handlePlaybackBoundary(mediaState.currentTimeSeconds * 1_000_000);
  }, [
    commitSeek,
    getMediaState,
    handlePlaybackBoundary,
    handleShuttleEnd,
    playbackModes,
    shuttleDirectionRef,
    startMediaPlayback,
    trimRef,
  ]);

  const onPlaybackError = useCallback(() => handlePausePlayback(), [handlePausePlayback]);

  return { onEnded, onLoadedMetadata, onPause, onPlay, onPlaybackError, onTimeUpdate };
}

export { useTimelineMediaEvents };
